import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LoginForm from "./FrontEndcode/Login/page";
import Navbar from "./FrontEndcode/Navbar/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <Navbar />
           <LoginForm />
        {children}
      </body>
    </html>
  );
}
